ALTER TABLE servers ADD COLUMN IF NOT EXISTS battlemetrics_id VARCHAR(50);
ALTER TABLE servers ADD COLUMN IF NOT EXISTS last_online INT DEFAULT 0;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS last_max INT DEFAULT 0;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS last_ping INT DEFAULT 0;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS last_status VARCHAR(10) DEFAULT 'unknown';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS last_checked TIMESTAMP;
